--<ScriptOptions statementTerminator=";"/>

CREATE TABLE RAW_DATA (
	ID INT NOT NULL,
	LINK VARCHAR(5500) NOT NULL,
	TERM_NAME VARCHAR(5500),
	BELONGS_TO_CATEGORY VARCHAR(5500),
	MAYBE_CAUSED_BY VARCHAR(30000),
	MAY_CAUSE VARCHAR(1500),
	MAY_BE_ASSOCIATED VARCHAR(1500),
	MAY_BE_RISK_FACTOR VARCHAR(1500),
	MAY_BE_CONTRAINDICATED VARCHAR(1500),
	MAY_INTERACT_WITH VARCHAR(1500),
	BELONGS_TO_DRUG_FAMILY VARCHAR(1500),
	MAY_BE_ALLELIC_TO VARCHAR(500),
	PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE MAY_CAUSE (
	ID INT NOT NULL,
	LINK VARCHAR(45),
	MAY_CAUSE VARCHAR(45),
	PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE MAYBE_CAUSED_BY (
	ID INT NOT NULL,
	LINK VARCHAR(45),
	MAYBE_CAUSED_BY VARCHAR(45),
	PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE CHEMDIS (
	ID INT NOT NULL,
	ChemicalName VARCHAR(5500),
	ChemicalID VARCHAR(300),
	CasRN VARCHAR(5500),
	DiseaseName VARCHAR(30000),
	DiseaseID VARCHAR(1500),
	DirectEvidence VARCHAR(1500),
	InferenceGeneSymbol VARCHAR(1500),
	InferenceScore VARCHAR(1500),
	OmimIDs VARCHAR(1500),
	PubMedIDs VARCHAR(1500),
	PRIMARY KEY (ID)
) ENGINE=InnoDB;

